spring:
  application:
    name: reporting-service

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
