ALTER TABLE venue
  ADD COLUMN description TEXT NULL,
  ADD COLUMN image_url VARCHAR(1024) NULL,
  ADD COLUMN phone VARCHAR(50) NULL,
  ADD COLUMN opening_time TIME NULL,
  ADD COLUMN closing_time TIME NULL,
  ADD COLUMN latitude DECIMAL(10,7) NULL,
  ADD COLUMN longitude DECIMAL(10,7) NULL;

ALTER TABLE product
  ADD COLUMN description TEXT NULL,
  ADD COLUMN image_url VARCHAR(1024) NULL,
  ADD COLUMN category VARCHAR(64) NULL,
  ADD COLUMN unit VARCHAR(64) NULL;
