CREATE TABLE notification_message (
  id BINARY(16) NOT NULL,
  status VARCHAR(32) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  recipient VARCHAR(128) NOT NULL,
  template_code VARCHAR(128) NULL,
  message TEXT NOT NULL,
  metadata_json TEXT NULL,
  source_topic VARCHAR(255) NULL,
  source_event_id VARCHAR(128) NULL,
  source_event_type VARCHAR(64) NULL,
  booking_id BINARY(16) NULL,
  payment_id BINARY(16) NULL,
  customer_id BINARY(16) NULL,
  trace_id VARCHAR(64) NULL,
  retry_count INT NOT NULL,
  next_attempt_at TIMESTAMP(6) NOT NULL,
  last_attempt_at TIMESTAMP(6) NULL,
  sent_at TIMESTAMP(6) NULL,
  last_error VARCHAR(1024) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_notification_event_recipient_template (source_event_id, channel, recipient, template_code),
  KEY idx_notification_status_next_attempt (status, next_attempt_at, created_at),
  KEY idx_notification_booking_created (booking_id, created_at),
  KEY idx_notification_customer_created (customer_id, created_at)
);
